// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-mall/app/front/admin/internal/biz"
	"kratos-mall/app/front/admin/internal/conf"
	"kratos-mall/app/front/admin/internal/data"
	"kratos-mall/app/front/admin/internal/server"
	"kratos-mall/app/front/admin/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(registry)
	umsClient := data.NewUmsServiceClient(discovery)
	payClient := data.NewPayServiceClient(discovery)
	pmsClient := data.NewPmsServiceClient(discovery)
	smsClient := data.NewSmsServiceClient(discovery)
	sysClient := data.NewSysServiceClient(discovery)
	omsClient := data.NewOmsServiceClient(discovery)
	dataData, err := data.NewData(logger, umsClient, payClient, pmsClient, smsClient, sysClient, omsClient)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
	}, nil
}
