// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SmsClient is the client API for Sms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmsClient interface {
	CouponAdd(ctx context.Context, in *CouponAddReq, opts ...grpc.CallOption) (*CouponAddResp, error)
	CouponList(ctx context.Context, in *CouponListReq, opts ...grpc.CallOption) (*CouponListResp, error)
	CouponUpdate(ctx context.Context, in *CouponUpdateReq, opts ...grpc.CallOption) (*CouponUpdateResp, error)
	CouponDelete(ctx context.Context, in *CouponDeleteReq, opts ...grpc.CallOption) (*CouponDeleteResp, error)
	CouponHistoryAdd(ctx context.Context, in *CouponHistoryAddReq, opts ...grpc.CallOption) (*CouponHistoryAddResp, error)
	CouponHistoryList(ctx context.Context, in *CouponHistoryListReq, opts ...grpc.CallOption) (*CouponHistoryListResp, error)
	CouponHistoryUpdate(ctx context.Context, in *CouponHistoryUpdateReq, opts ...grpc.CallOption) (*CouponHistoryUpdateResp, error)
	CouponHistoryDelete(ctx context.Context, in *CouponHistoryDeleteReq, opts ...grpc.CallOption) (*CouponHistoryDeleteResp, error)
	FlashPromotionLogAdd(ctx context.Context, in *FlashPromotionLogAddReq, opts ...grpc.CallOption) (*FlashPromotionLogAddResp, error)
	FlashPromotionLogList(ctx context.Context, in *FlashPromotionLogListReq, opts ...grpc.CallOption) (*FlashPromotionLogListResp, error)
	FlashPromotionLogUpdate(ctx context.Context, in *FlashPromotionLogUpdateReq, opts ...grpc.CallOption) (*FlashPromotionLogUpdateResp, error)
	FlashPromotionLogDelete(ctx context.Context, in *FlashPromotionLogDeleteReq, opts ...grpc.CallOption) (*FlashPromotionLogDeleteResp, error)
	FlashPromotionAdd(ctx context.Context, in *FlashPromotionAddReq, opts ...grpc.CallOption) (*FlashPromotionAddResp, error)
	FlashPromotionList(ctx context.Context, in *FlashPromotionListReq, opts ...grpc.CallOption) (*FlashPromotionListResp, error)
	FlashPromotionUpdate(ctx context.Context, in *FlashPromotionUpdateReq, opts ...grpc.CallOption) (*FlashPromotionUpdateResp, error)
	FlashPromotionDelete(ctx context.Context, in *FlashPromotionDeleteReq, opts ...grpc.CallOption) (*FlashPromotionDeleteResp, error)
	FlashPromotionSessionAdd(ctx context.Context, in *FlashPromotionSessionAddReq, opts ...grpc.CallOption) (*FlashPromotionSessionAddResp, error)
	FlashPromotionSessionList(ctx context.Context, in *FlashPromotionSessionListReq, opts ...grpc.CallOption) (*FlashPromotionSessionListResp, error)
	FlashPromotionSessionUpdate(ctx context.Context, in *FlashPromotionSessionUpdateReq, opts ...grpc.CallOption) (*FlashPromotionSessionUpdateResp, error)
	FlashPromotionSessionDelete(ctx context.Context, in *FlashPromotionSessionDeleteReq, opts ...grpc.CallOption) (*FlashPromotionSessionDeleteResp, error)
	HomeAdvertiseAdd(ctx context.Context, in *HomeAdvertiseAddReq, opts ...grpc.CallOption) (*HomeAdvertiseAddResp, error)
	HomeAdvertiseList(ctx context.Context, in *HomeAdvertiseListReq, opts ...grpc.CallOption) (*HomeAdvertiseListResp, error)
	HomeAdvertiseUpdate(ctx context.Context, in *HomeAdvertiseUpdateReq, opts ...grpc.CallOption) (*HomeAdvertiseUpdateResp, error)
	HomeAdvertiseDelete(ctx context.Context, in *HomeAdvertiseDeleteReq, opts ...grpc.CallOption) (*HomeAdvertiseDeleteResp, error)
	HomeBrandAdd(ctx context.Context, in *HomeBrandAddReq, opts ...grpc.CallOption) (*HomeBrandAddResp, error)
	HomeBrandList(ctx context.Context, in *HomeBrandListReq, opts ...grpc.CallOption) (*HomeBrandListResp, error)
	HomeBrandUpdate(ctx context.Context, in *HomeBrandUpdateReq, opts ...grpc.CallOption) (*HomeBrandUpdateResp, error)
	HomeBrandDelete(ctx context.Context, in *HomeBrandDeleteReq, opts ...grpc.CallOption) (*HomeBrandDeleteResp, error)
	HomeNewProductAdd(ctx context.Context, in *HomeNewProductAddReq, opts ...grpc.CallOption) (*HomeNewProductAddResp, error)
	HomeNewProductList(ctx context.Context, in *HomeNewProductListReq, opts ...grpc.CallOption) (*HomeNewProductListResp, error)
	HomeNewProductUpdate(ctx context.Context, in *HomeNewProductUpdateReq, opts ...grpc.CallOption) (*HomeNewProductUpdateResp, error)
	HomeNewProductDelete(ctx context.Context, in *HomeNewProductDeleteReq, opts ...grpc.CallOption) (*HomeNewProductDeleteResp, error)
	HomeRecommendProductAdd(ctx context.Context, in *HomeRecommendProductAddReq, opts ...grpc.CallOption) (*HomeRecommendProductAddResp, error)
	HomeRecommendProductList(ctx context.Context, in *HomeRecommendProductListReq, opts ...grpc.CallOption) (*HomeRecommendProductListResp, error)
	HomeRecommendProductUpdate(ctx context.Context, in *HomeRecommendProductUpdateReq, opts ...grpc.CallOption) (*HomeRecommendProductUpdateResp, error)
	HomeRecommendProductDelete(ctx context.Context, in *HomeRecommendProductDeleteReq, opts ...grpc.CallOption) (*HomeRecommendProductDeleteResp, error)
	HomeRecommendSubjectAdd(ctx context.Context, in *HomeRecommendSubjectAddReq, opts ...grpc.CallOption) (*HomeRecommendSubjectAddResp, error)
	HomeRecommendSubjectList(ctx context.Context, in *HomeRecommendSubjectListReq, opts ...grpc.CallOption) (*HomeRecommendSubjectListResp, error)
	HomeRecommendSubjectUpdate(ctx context.Context, in *HomeRecommendSubjectUpdateReq, opts ...grpc.CallOption) (*HomeRecommendSubjectUpdateResp, error)
	HomeRecommendSubjectDelete(ctx context.Context, in *HomeRecommendSubjectDeleteReq, opts ...grpc.CallOption) (*HomeRecommendSubjectDeleteResp, error)
}

type smsClient struct {
	cc grpc.ClientConnInterface
}

func NewSmsClient(cc grpc.ClientConnInterface) SmsClient {
	return &smsClient{cc}
}

func (c *smsClient) CouponAdd(ctx context.Context, in *CouponAddReq, opts ...grpc.CallOption) (*CouponAddResp, error) {
	out := new(CouponAddResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/CouponAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) CouponList(ctx context.Context, in *CouponListReq, opts ...grpc.CallOption) (*CouponListResp, error) {
	out := new(CouponListResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/CouponList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) CouponUpdate(ctx context.Context, in *CouponUpdateReq, opts ...grpc.CallOption) (*CouponUpdateResp, error) {
	out := new(CouponUpdateResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/CouponUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) CouponDelete(ctx context.Context, in *CouponDeleteReq, opts ...grpc.CallOption) (*CouponDeleteResp, error) {
	out := new(CouponDeleteResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/CouponDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) CouponHistoryAdd(ctx context.Context, in *CouponHistoryAddReq, opts ...grpc.CallOption) (*CouponHistoryAddResp, error) {
	out := new(CouponHistoryAddResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/CouponHistoryAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) CouponHistoryList(ctx context.Context, in *CouponHistoryListReq, opts ...grpc.CallOption) (*CouponHistoryListResp, error) {
	out := new(CouponHistoryListResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/CouponHistoryList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) CouponHistoryUpdate(ctx context.Context, in *CouponHistoryUpdateReq, opts ...grpc.CallOption) (*CouponHistoryUpdateResp, error) {
	out := new(CouponHistoryUpdateResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/CouponHistoryUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) CouponHistoryDelete(ctx context.Context, in *CouponHistoryDeleteReq, opts ...grpc.CallOption) (*CouponHistoryDeleteResp, error) {
	out := new(CouponHistoryDeleteResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/CouponHistoryDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) FlashPromotionLogAdd(ctx context.Context, in *FlashPromotionLogAddReq, opts ...grpc.CallOption) (*FlashPromotionLogAddResp, error) {
	out := new(FlashPromotionLogAddResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/FlashPromotionLogAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) FlashPromotionLogList(ctx context.Context, in *FlashPromotionLogListReq, opts ...grpc.CallOption) (*FlashPromotionLogListResp, error) {
	out := new(FlashPromotionLogListResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/FlashPromotionLogList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) FlashPromotionLogUpdate(ctx context.Context, in *FlashPromotionLogUpdateReq, opts ...grpc.CallOption) (*FlashPromotionLogUpdateResp, error) {
	out := new(FlashPromotionLogUpdateResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/FlashPromotionLogUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) FlashPromotionLogDelete(ctx context.Context, in *FlashPromotionLogDeleteReq, opts ...grpc.CallOption) (*FlashPromotionLogDeleteResp, error) {
	out := new(FlashPromotionLogDeleteResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/FlashPromotionLogDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) FlashPromotionAdd(ctx context.Context, in *FlashPromotionAddReq, opts ...grpc.CallOption) (*FlashPromotionAddResp, error) {
	out := new(FlashPromotionAddResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/FlashPromotionAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) FlashPromotionList(ctx context.Context, in *FlashPromotionListReq, opts ...grpc.CallOption) (*FlashPromotionListResp, error) {
	out := new(FlashPromotionListResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/FlashPromotionList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) FlashPromotionUpdate(ctx context.Context, in *FlashPromotionUpdateReq, opts ...grpc.CallOption) (*FlashPromotionUpdateResp, error) {
	out := new(FlashPromotionUpdateResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/FlashPromotionUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) FlashPromotionDelete(ctx context.Context, in *FlashPromotionDeleteReq, opts ...grpc.CallOption) (*FlashPromotionDeleteResp, error) {
	out := new(FlashPromotionDeleteResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/FlashPromotionDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) FlashPromotionSessionAdd(ctx context.Context, in *FlashPromotionSessionAddReq, opts ...grpc.CallOption) (*FlashPromotionSessionAddResp, error) {
	out := new(FlashPromotionSessionAddResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/FlashPromotionSessionAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) FlashPromotionSessionList(ctx context.Context, in *FlashPromotionSessionListReq, opts ...grpc.CallOption) (*FlashPromotionSessionListResp, error) {
	out := new(FlashPromotionSessionListResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/FlashPromotionSessionList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) FlashPromotionSessionUpdate(ctx context.Context, in *FlashPromotionSessionUpdateReq, opts ...grpc.CallOption) (*FlashPromotionSessionUpdateResp, error) {
	out := new(FlashPromotionSessionUpdateResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/FlashPromotionSessionUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) FlashPromotionSessionDelete(ctx context.Context, in *FlashPromotionSessionDeleteReq, opts ...grpc.CallOption) (*FlashPromotionSessionDeleteResp, error) {
	out := new(FlashPromotionSessionDeleteResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/FlashPromotionSessionDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeAdvertiseAdd(ctx context.Context, in *HomeAdvertiseAddReq, opts ...grpc.CallOption) (*HomeAdvertiseAddResp, error) {
	out := new(HomeAdvertiseAddResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeAdvertiseAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeAdvertiseList(ctx context.Context, in *HomeAdvertiseListReq, opts ...grpc.CallOption) (*HomeAdvertiseListResp, error) {
	out := new(HomeAdvertiseListResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeAdvertiseList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeAdvertiseUpdate(ctx context.Context, in *HomeAdvertiseUpdateReq, opts ...grpc.CallOption) (*HomeAdvertiseUpdateResp, error) {
	out := new(HomeAdvertiseUpdateResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeAdvertiseUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeAdvertiseDelete(ctx context.Context, in *HomeAdvertiseDeleteReq, opts ...grpc.CallOption) (*HomeAdvertiseDeleteResp, error) {
	out := new(HomeAdvertiseDeleteResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeAdvertiseDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeBrandAdd(ctx context.Context, in *HomeBrandAddReq, opts ...grpc.CallOption) (*HomeBrandAddResp, error) {
	out := new(HomeBrandAddResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeBrandAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeBrandList(ctx context.Context, in *HomeBrandListReq, opts ...grpc.CallOption) (*HomeBrandListResp, error) {
	out := new(HomeBrandListResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeBrandList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeBrandUpdate(ctx context.Context, in *HomeBrandUpdateReq, opts ...grpc.CallOption) (*HomeBrandUpdateResp, error) {
	out := new(HomeBrandUpdateResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeBrandUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeBrandDelete(ctx context.Context, in *HomeBrandDeleteReq, opts ...grpc.CallOption) (*HomeBrandDeleteResp, error) {
	out := new(HomeBrandDeleteResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeBrandDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeNewProductAdd(ctx context.Context, in *HomeNewProductAddReq, opts ...grpc.CallOption) (*HomeNewProductAddResp, error) {
	out := new(HomeNewProductAddResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeNewProductAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeNewProductList(ctx context.Context, in *HomeNewProductListReq, opts ...grpc.CallOption) (*HomeNewProductListResp, error) {
	out := new(HomeNewProductListResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeNewProductList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeNewProductUpdate(ctx context.Context, in *HomeNewProductUpdateReq, opts ...grpc.CallOption) (*HomeNewProductUpdateResp, error) {
	out := new(HomeNewProductUpdateResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeNewProductUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeNewProductDelete(ctx context.Context, in *HomeNewProductDeleteReq, opts ...grpc.CallOption) (*HomeNewProductDeleteResp, error) {
	out := new(HomeNewProductDeleteResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeNewProductDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeRecommendProductAdd(ctx context.Context, in *HomeRecommendProductAddReq, opts ...grpc.CallOption) (*HomeRecommendProductAddResp, error) {
	out := new(HomeRecommendProductAddResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeRecommendProductAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeRecommendProductList(ctx context.Context, in *HomeRecommendProductListReq, opts ...grpc.CallOption) (*HomeRecommendProductListResp, error) {
	out := new(HomeRecommendProductListResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeRecommendProductList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeRecommendProductUpdate(ctx context.Context, in *HomeRecommendProductUpdateReq, opts ...grpc.CallOption) (*HomeRecommendProductUpdateResp, error) {
	out := new(HomeRecommendProductUpdateResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeRecommendProductUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeRecommendProductDelete(ctx context.Context, in *HomeRecommendProductDeleteReq, opts ...grpc.CallOption) (*HomeRecommendProductDeleteResp, error) {
	out := new(HomeRecommendProductDeleteResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeRecommendProductDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeRecommendSubjectAdd(ctx context.Context, in *HomeRecommendSubjectAddReq, opts ...grpc.CallOption) (*HomeRecommendSubjectAddResp, error) {
	out := new(HomeRecommendSubjectAddResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeRecommendSubjectAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeRecommendSubjectList(ctx context.Context, in *HomeRecommendSubjectListReq, opts ...grpc.CallOption) (*HomeRecommendSubjectListResp, error) {
	out := new(HomeRecommendSubjectListResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeRecommendSubjectList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeRecommendSubjectUpdate(ctx context.Context, in *HomeRecommendSubjectUpdateReq, opts ...grpc.CallOption) (*HomeRecommendSubjectUpdateResp, error) {
	out := new(HomeRecommendSubjectUpdateResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeRecommendSubjectUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeRecommendSubjectDelete(ctx context.Context, in *HomeRecommendSubjectDeleteReq, opts ...grpc.CallOption) (*HomeRecommendSubjectDeleteResp, error) {
	out := new(HomeRecommendSubjectDeleteResp)
	err := c.cc.Invoke(ctx, "/front.admin.v1.Sms/HomeRecommendSubjectDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmsServer is the server API for Sms service.
// All implementations must embed UnimplementedSmsServer
// for forward compatibility
type SmsServer interface {
	CouponAdd(context.Context, *CouponAddReq) (*CouponAddResp, error)
	CouponList(context.Context, *CouponListReq) (*CouponListResp, error)
	CouponUpdate(context.Context, *CouponUpdateReq) (*CouponUpdateResp, error)
	CouponDelete(context.Context, *CouponDeleteReq) (*CouponDeleteResp, error)
	CouponHistoryAdd(context.Context, *CouponHistoryAddReq) (*CouponHistoryAddResp, error)
	CouponHistoryList(context.Context, *CouponHistoryListReq) (*CouponHistoryListResp, error)
	CouponHistoryUpdate(context.Context, *CouponHistoryUpdateReq) (*CouponHistoryUpdateResp, error)
	CouponHistoryDelete(context.Context, *CouponHistoryDeleteReq) (*CouponHistoryDeleteResp, error)
	FlashPromotionLogAdd(context.Context, *FlashPromotionLogAddReq) (*FlashPromotionLogAddResp, error)
	FlashPromotionLogList(context.Context, *FlashPromotionLogListReq) (*FlashPromotionLogListResp, error)
	FlashPromotionLogUpdate(context.Context, *FlashPromotionLogUpdateReq) (*FlashPromotionLogUpdateResp, error)
	FlashPromotionLogDelete(context.Context, *FlashPromotionLogDeleteReq) (*FlashPromotionLogDeleteResp, error)
	FlashPromotionAdd(context.Context, *FlashPromotionAddReq) (*FlashPromotionAddResp, error)
	FlashPromotionList(context.Context, *FlashPromotionListReq) (*FlashPromotionListResp, error)
	FlashPromotionUpdate(context.Context, *FlashPromotionUpdateReq) (*FlashPromotionUpdateResp, error)
	FlashPromotionDelete(context.Context, *FlashPromotionDeleteReq) (*FlashPromotionDeleteResp, error)
	FlashPromotionSessionAdd(context.Context, *FlashPromotionSessionAddReq) (*FlashPromotionSessionAddResp, error)
	FlashPromotionSessionList(context.Context, *FlashPromotionSessionListReq) (*FlashPromotionSessionListResp, error)
	FlashPromotionSessionUpdate(context.Context, *FlashPromotionSessionUpdateReq) (*FlashPromotionSessionUpdateResp, error)
	FlashPromotionSessionDelete(context.Context, *FlashPromotionSessionDeleteReq) (*FlashPromotionSessionDeleteResp, error)
	HomeAdvertiseAdd(context.Context, *HomeAdvertiseAddReq) (*HomeAdvertiseAddResp, error)
	HomeAdvertiseList(context.Context, *HomeAdvertiseListReq) (*HomeAdvertiseListResp, error)
	HomeAdvertiseUpdate(context.Context, *HomeAdvertiseUpdateReq) (*HomeAdvertiseUpdateResp, error)
	HomeAdvertiseDelete(context.Context, *HomeAdvertiseDeleteReq) (*HomeAdvertiseDeleteResp, error)
	HomeBrandAdd(context.Context, *HomeBrandAddReq) (*HomeBrandAddResp, error)
	HomeBrandList(context.Context, *HomeBrandListReq) (*HomeBrandListResp, error)
	HomeBrandUpdate(context.Context, *HomeBrandUpdateReq) (*HomeBrandUpdateResp, error)
	HomeBrandDelete(context.Context, *HomeBrandDeleteReq) (*HomeBrandDeleteResp, error)
	HomeNewProductAdd(context.Context, *HomeNewProductAddReq) (*HomeNewProductAddResp, error)
	HomeNewProductList(context.Context, *HomeNewProductListReq) (*HomeNewProductListResp, error)
	HomeNewProductUpdate(context.Context, *HomeNewProductUpdateReq) (*HomeNewProductUpdateResp, error)
	HomeNewProductDelete(context.Context, *HomeNewProductDeleteReq) (*HomeNewProductDeleteResp, error)
	HomeRecommendProductAdd(context.Context, *HomeRecommendProductAddReq) (*HomeRecommendProductAddResp, error)
	HomeRecommendProductList(context.Context, *HomeRecommendProductListReq) (*HomeRecommendProductListResp, error)
	HomeRecommendProductUpdate(context.Context, *HomeRecommendProductUpdateReq) (*HomeRecommendProductUpdateResp, error)
	HomeRecommendProductDelete(context.Context, *HomeRecommendProductDeleteReq) (*HomeRecommendProductDeleteResp, error)
	HomeRecommendSubjectAdd(context.Context, *HomeRecommendSubjectAddReq) (*HomeRecommendSubjectAddResp, error)
	HomeRecommendSubjectList(context.Context, *HomeRecommendSubjectListReq) (*HomeRecommendSubjectListResp, error)
	HomeRecommendSubjectUpdate(context.Context, *HomeRecommendSubjectUpdateReq) (*HomeRecommendSubjectUpdateResp, error)
	HomeRecommendSubjectDelete(context.Context, *HomeRecommendSubjectDeleteReq) (*HomeRecommendSubjectDeleteResp, error)
	mustEmbedUnimplementedSmsServer()
}

// UnimplementedSmsServer must be embedded to have forward compatible implementations.
type UnimplementedSmsServer struct {
}

func (UnimplementedSmsServer) CouponAdd(context.Context, *CouponAddReq) (*CouponAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponAdd not implemented")
}
func (UnimplementedSmsServer) CouponList(context.Context, *CouponListReq) (*CouponListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponList not implemented")
}
func (UnimplementedSmsServer) CouponUpdate(context.Context, *CouponUpdateReq) (*CouponUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponUpdate not implemented")
}
func (UnimplementedSmsServer) CouponDelete(context.Context, *CouponDeleteReq) (*CouponDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponDelete not implemented")
}
func (UnimplementedSmsServer) CouponHistoryAdd(context.Context, *CouponHistoryAddReq) (*CouponHistoryAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponHistoryAdd not implemented")
}
func (UnimplementedSmsServer) CouponHistoryList(context.Context, *CouponHistoryListReq) (*CouponHistoryListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponHistoryList not implemented")
}
func (UnimplementedSmsServer) CouponHistoryUpdate(context.Context, *CouponHistoryUpdateReq) (*CouponHistoryUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponHistoryUpdate not implemented")
}
func (UnimplementedSmsServer) CouponHistoryDelete(context.Context, *CouponHistoryDeleteReq) (*CouponHistoryDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponHistoryDelete not implemented")
}
func (UnimplementedSmsServer) FlashPromotionLogAdd(context.Context, *FlashPromotionLogAddReq) (*FlashPromotionLogAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlashPromotionLogAdd not implemented")
}
func (UnimplementedSmsServer) FlashPromotionLogList(context.Context, *FlashPromotionLogListReq) (*FlashPromotionLogListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlashPromotionLogList not implemented")
}
func (UnimplementedSmsServer) FlashPromotionLogUpdate(context.Context, *FlashPromotionLogUpdateReq) (*FlashPromotionLogUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlashPromotionLogUpdate not implemented")
}
func (UnimplementedSmsServer) FlashPromotionLogDelete(context.Context, *FlashPromotionLogDeleteReq) (*FlashPromotionLogDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlashPromotionLogDelete not implemented")
}
func (UnimplementedSmsServer) FlashPromotionAdd(context.Context, *FlashPromotionAddReq) (*FlashPromotionAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlashPromotionAdd not implemented")
}
func (UnimplementedSmsServer) FlashPromotionList(context.Context, *FlashPromotionListReq) (*FlashPromotionListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlashPromotionList not implemented")
}
func (UnimplementedSmsServer) FlashPromotionUpdate(context.Context, *FlashPromotionUpdateReq) (*FlashPromotionUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlashPromotionUpdate not implemented")
}
func (UnimplementedSmsServer) FlashPromotionDelete(context.Context, *FlashPromotionDeleteReq) (*FlashPromotionDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlashPromotionDelete not implemented")
}
func (UnimplementedSmsServer) FlashPromotionSessionAdd(context.Context, *FlashPromotionSessionAddReq) (*FlashPromotionSessionAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlashPromotionSessionAdd not implemented")
}
func (UnimplementedSmsServer) FlashPromotionSessionList(context.Context, *FlashPromotionSessionListReq) (*FlashPromotionSessionListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlashPromotionSessionList not implemented")
}
func (UnimplementedSmsServer) FlashPromotionSessionUpdate(context.Context, *FlashPromotionSessionUpdateReq) (*FlashPromotionSessionUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlashPromotionSessionUpdate not implemented")
}
func (UnimplementedSmsServer) FlashPromotionSessionDelete(context.Context, *FlashPromotionSessionDeleteReq) (*FlashPromotionSessionDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlashPromotionSessionDelete not implemented")
}
func (UnimplementedSmsServer) HomeAdvertiseAdd(context.Context, *HomeAdvertiseAddReq) (*HomeAdvertiseAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeAdvertiseAdd not implemented")
}
func (UnimplementedSmsServer) HomeAdvertiseList(context.Context, *HomeAdvertiseListReq) (*HomeAdvertiseListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeAdvertiseList not implemented")
}
func (UnimplementedSmsServer) HomeAdvertiseUpdate(context.Context, *HomeAdvertiseUpdateReq) (*HomeAdvertiseUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeAdvertiseUpdate not implemented")
}
func (UnimplementedSmsServer) HomeAdvertiseDelete(context.Context, *HomeAdvertiseDeleteReq) (*HomeAdvertiseDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeAdvertiseDelete not implemented")
}
func (UnimplementedSmsServer) HomeBrandAdd(context.Context, *HomeBrandAddReq) (*HomeBrandAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeBrandAdd not implemented")
}
func (UnimplementedSmsServer) HomeBrandList(context.Context, *HomeBrandListReq) (*HomeBrandListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeBrandList not implemented")
}
func (UnimplementedSmsServer) HomeBrandUpdate(context.Context, *HomeBrandUpdateReq) (*HomeBrandUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeBrandUpdate not implemented")
}
func (UnimplementedSmsServer) HomeBrandDelete(context.Context, *HomeBrandDeleteReq) (*HomeBrandDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeBrandDelete not implemented")
}
func (UnimplementedSmsServer) HomeNewProductAdd(context.Context, *HomeNewProductAddReq) (*HomeNewProductAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeNewProductAdd not implemented")
}
func (UnimplementedSmsServer) HomeNewProductList(context.Context, *HomeNewProductListReq) (*HomeNewProductListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeNewProductList not implemented")
}
func (UnimplementedSmsServer) HomeNewProductUpdate(context.Context, *HomeNewProductUpdateReq) (*HomeNewProductUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeNewProductUpdate not implemented")
}
func (UnimplementedSmsServer) HomeNewProductDelete(context.Context, *HomeNewProductDeleteReq) (*HomeNewProductDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeNewProductDelete not implemented")
}
func (UnimplementedSmsServer) HomeRecommendProductAdd(context.Context, *HomeRecommendProductAddReq) (*HomeRecommendProductAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeRecommendProductAdd not implemented")
}
func (UnimplementedSmsServer) HomeRecommendProductList(context.Context, *HomeRecommendProductListReq) (*HomeRecommendProductListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeRecommendProductList not implemented")
}
func (UnimplementedSmsServer) HomeRecommendProductUpdate(context.Context, *HomeRecommendProductUpdateReq) (*HomeRecommendProductUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeRecommendProductUpdate not implemented")
}
func (UnimplementedSmsServer) HomeRecommendProductDelete(context.Context, *HomeRecommendProductDeleteReq) (*HomeRecommendProductDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeRecommendProductDelete not implemented")
}
func (UnimplementedSmsServer) HomeRecommendSubjectAdd(context.Context, *HomeRecommendSubjectAddReq) (*HomeRecommendSubjectAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeRecommendSubjectAdd not implemented")
}
func (UnimplementedSmsServer) HomeRecommendSubjectList(context.Context, *HomeRecommendSubjectListReq) (*HomeRecommendSubjectListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeRecommendSubjectList not implemented")
}
func (UnimplementedSmsServer) HomeRecommendSubjectUpdate(context.Context, *HomeRecommendSubjectUpdateReq) (*HomeRecommendSubjectUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeRecommendSubjectUpdate not implemented")
}
func (UnimplementedSmsServer) HomeRecommendSubjectDelete(context.Context, *HomeRecommendSubjectDeleteReq) (*HomeRecommendSubjectDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeRecommendSubjectDelete not implemented")
}
func (UnimplementedSmsServer) mustEmbedUnimplementedSmsServer() {}

// UnsafeSmsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmsServer will
// result in compilation errors.
type UnsafeSmsServer interface {
	mustEmbedUnimplementedSmsServer()
}

func RegisterSmsServer(s grpc.ServiceRegistrar, srv SmsServer) {
	s.RegisterService(&Sms_ServiceDesc, srv)
}

func _Sms_CouponAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).CouponAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/CouponAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).CouponAdd(ctx, req.(*CouponAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_CouponList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).CouponList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/CouponList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).CouponList(ctx, req.(*CouponListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_CouponUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).CouponUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/CouponUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).CouponUpdate(ctx, req.(*CouponUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_CouponDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).CouponDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/CouponDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).CouponDelete(ctx, req.(*CouponDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_CouponHistoryAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponHistoryAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).CouponHistoryAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/CouponHistoryAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).CouponHistoryAdd(ctx, req.(*CouponHistoryAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_CouponHistoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponHistoryListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).CouponHistoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/CouponHistoryList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).CouponHistoryList(ctx, req.(*CouponHistoryListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_CouponHistoryUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponHistoryUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).CouponHistoryUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/CouponHistoryUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).CouponHistoryUpdate(ctx, req.(*CouponHistoryUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_CouponHistoryDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponHistoryDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).CouponHistoryDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/CouponHistoryDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).CouponHistoryDelete(ctx, req.(*CouponHistoryDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_FlashPromotionLogAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashPromotionLogAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).FlashPromotionLogAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/FlashPromotionLogAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).FlashPromotionLogAdd(ctx, req.(*FlashPromotionLogAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_FlashPromotionLogList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashPromotionLogListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).FlashPromotionLogList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/FlashPromotionLogList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).FlashPromotionLogList(ctx, req.(*FlashPromotionLogListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_FlashPromotionLogUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashPromotionLogUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).FlashPromotionLogUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/FlashPromotionLogUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).FlashPromotionLogUpdate(ctx, req.(*FlashPromotionLogUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_FlashPromotionLogDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashPromotionLogDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).FlashPromotionLogDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/FlashPromotionLogDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).FlashPromotionLogDelete(ctx, req.(*FlashPromotionLogDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_FlashPromotionAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashPromotionAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).FlashPromotionAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/FlashPromotionAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).FlashPromotionAdd(ctx, req.(*FlashPromotionAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_FlashPromotionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashPromotionListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).FlashPromotionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/FlashPromotionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).FlashPromotionList(ctx, req.(*FlashPromotionListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_FlashPromotionUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashPromotionUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).FlashPromotionUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/FlashPromotionUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).FlashPromotionUpdate(ctx, req.(*FlashPromotionUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_FlashPromotionDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashPromotionDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).FlashPromotionDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/FlashPromotionDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).FlashPromotionDelete(ctx, req.(*FlashPromotionDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_FlashPromotionSessionAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashPromotionSessionAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).FlashPromotionSessionAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/FlashPromotionSessionAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).FlashPromotionSessionAdd(ctx, req.(*FlashPromotionSessionAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_FlashPromotionSessionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashPromotionSessionListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).FlashPromotionSessionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/FlashPromotionSessionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).FlashPromotionSessionList(ctx, req.(*FlashPromotionSessionListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_FlashPromotionSessionUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashPromotionSessionUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).FlashPromotionSessionUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/FlashPromotionSessionUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).FlashPromotionSessionUpdate(ctx, req.(*FlashPromotionSessionUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_FlashPromotionSessionDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashPromotionSessionDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).FlashPromotionSessionDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/FlashPromotionSessionDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).FlashPromotionSessionDelete(ctx, req.(*FlashPromotionSessionDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeAdvertiseAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeAdvertiseAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeAdvertiseAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeAdvertiseAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeAdvertiseAdd(ctx, req.(*HomeAdvertiseAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeAdvertiseList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeAdvertiseListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeAdvertiseList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeAdvertiseList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeAdvertiseList(ctx, req.(*HomeAdvertiseListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeAdvertiseUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeAdvertiseUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeAdvertiseUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeAdvertiseUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeAdvertiseUpdate(ctx, req.(*HomeAdvertiseUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeAdvertiseDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeAdvertiseDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeAdvertiseDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeAdvertiseDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeAdvertiseDelete(ctx, req.(*HomeAdvertiseDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeBrandAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeBrandAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeBrandAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeBrandAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeBrandAdd(ctx, req.(*HomeBrandAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeBrandList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeBrandListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeBrandList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeBrandList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeBrandList(ctx, req.(*HomeBrandListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeBrandUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeBrandUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeBrandUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeBrandUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeBrandUpdate(ctx, req.(*HomeBrandUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeBrandDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeBrandDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeBrandDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeBrandDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeBrandDelete(ctx, req.(*HomeBrandDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeNewProductAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeNewProductAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeNewProductAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeNewProductAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeNewProductAdd(ctx, req.(*HomeNewProductAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeNewProductList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeNewProductListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeNewProductList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeNewProductList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeNewProductList(ctx, req.(*HomeNewProductListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeNewProductUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeNewProductUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeNewProductUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeNewProductUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeNewProductUpdate(ctx, req.(*HomeNewProductUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeNewProductDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeNewProductDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeNewProductDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeNewProductDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeNewProductDelete(ctx, req.(*HomeNewProductDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeRecommendProductAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeRecommendProductAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeRecommendProductAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeRecommendProductAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeRecommendProductAdd(ctx, req.(*HomeRecommendProductAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeRecommendProductList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeRecommendProductListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeRecommendProductList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeRecommendProductList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeRecommendProductList(ctx, req.(*HomeRecommendProductListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeRecommendProductUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeRecommendProductUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeRecommendProductUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeRecommendProductUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeRecommendProductUpdate(ctx, req.(*HomeRecommendProductUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeRecommendProductDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeRecommendProductDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeRecommendProductDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeRecommendProductDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeRecommendProductDelete(ctx, req.(*HomeRecommendProductDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeRecommendSubjectAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeRecommendSubjectAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeRecommendSubjectAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeRecommendSubjectAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeRecommendSubjectAdd(ctx, req.(*HomeRecommendSubjectAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeRecommendSubjectList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeRecommendSubjectListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeRecommendSubjectList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeRecommendSubjectList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeRecommendSubjectList(ctx, req.(*HomeRecommendSubjectListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeRecommendSubjectUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeRecommendSubjectUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeRecommendSubjectUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeRecommendSubjectUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeRecommendSubjectUpdate(ctx, req.(*HomeRecommendSubjectUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeRecommendSubjectDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeRecommendSubjectDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeRecommendSubjectDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/front.admin.v1.Sms/HomeRecommendSubjectDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeRecommendSubjectDelete(ctx, req.(*HomeRecommendSubjectDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Sms_ServiceDesc is the grpc.ServiceDesc for Sms service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sms_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "front.admin.v1.Sms",
	HandlerType: (*SmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CouponAdd",
			Handler:    _Sms_CouponAdd_Handler,
		},
		{
			MethodName: "CouponList",
			Handler:    _Sms_CouponList_Handler,
		},
		{
			MethodName: "CouponUpdate",
			Handler:    _Sms_CouponUpdate_Handler,
		},
		{
			MethodName: "CouponDelete",
			Handler:    _Sms_CouponDelete_Handler,
		},
		{
			MethodName: "CouponHistoryAdd",
			Handler:    _Sms_CouponHistoryAdd_Handler,
		},
		{
			MethodName: "CouponHistoryList",
			Handler:    _Sms_CouponHistoryList_Handler,
		},
		{
			MethodName: "CouponHistoryUpdate",
			Handler:    _Sms_CouponHistoryUpdate_Handler,
		},
		{
			MethodName: "CouponHistoryDelete",
			Handler:    _Sms_CouponHistoryDelete_Handler,
		},
		{
			MethodName: "FlashPromotionLogAdd",
			Handler:    _Sms_FlashPromotionLogAdd_Handler,
		},
		{
			MethodName: "FlashPromotionLogList",
			Handler:    _Sms_FlashPromotionLogList_Handler,
		},
		{
			MethodName: "FlashPromotionLogUpdate",
			Handler:    _Sms_FlashPromotionLogUpdate_Handler,
		},
		{
			MethodName: "FlashPromotionLogDelete",
			Handler:    _Sms_FlashPromotionLogDelete_Handler,
		},
		{
			MethodName: "FlashPromotionAdd",
			Handler:    _Sms_FlashPromotionAdd_Handler,
		},
		{
			MethodName: "FlashPromotionList",
			Handler:    _Sms_FlashPromotionList_Handler,
		},
		{
			MethodName: "FlashPromotionUpdate",
			Handler:    _Sms_FlashPromotionUpdate_Handler,
		},
		{
			MethodName: "FlashPromotionDelete",
			Handler:    _Sms_FlashPromotionDelete_Handler,
		},
		{
			MethodName: "FlashPromotionSessionAdd",
			Handler:    _Sms_FlashPromotionSessionAdd_Handler,
		},
		{
			MethodName: "FlashPromotionSessionList",
			Handler:    _Sms_FlashPromotionSessionList_Handler,
		},
		{
			MethodName: "FlashPromotionSessionUpdate",
			Handler:    _Sms_FlashPromotionSessionUpdate_Handler,
		},
		{
			MethodName: "FlashPromotionSessionDelete",
			Handler:    _Sms_FlashPromotionSessionDelete_Handler,
		},
		{
			MethodName: "HomeAdvertiseAdd",
			Handler:    _Sms_HomeAdvertiseAdd_Handler,
		},
		{
			MethodName: "HomeAdvertiseList",
			Handler:    _Sms_HomeAdvertiseList_Handler,
		},
		{
			MethodName: "HomeAdvertiseUpdate",
			Handler:    _Sms_HomeAdvertiseUpdate_Handler,
		},
		{
			MethodName: "HomeAdvertiseDelete",
			Handler:    _Sms_HomeAdvertiseDelete_Handler,
		},
		{
			MethodName: "HomeBrandAdd",
			Handler:    _Sms_HomeBrandAdd_Handler,
		},
		{
			MethodName: "HomeBrandList",
			Handler:    _Sms_HomeBrandList_Handler,
		},
		{
			MethodName: "HomeBrandUpdate",
			Handler:    _Sms_HomeBrandUpdate_Handler,
		},
		{
			MethodName: "HomeBrandDelete",
			Handler:    _Sms_HomeBrandDelete_Handler,
		},
		{
			MethodName: "HomeNewProductAdd",
			Handler:    _Sms_HomeNewProductAdd_Handler,
		},
		{
			MethodName: "HomeNewProductList",
			Handler:    _Sms_HomeNewProductList_Handler,
		},
		{
			MethodName: "HomeNewProductUpdate",
			Handler:    _Sms_HomeNewProductUpdate_Handler,
		},
		{
			MethodName: "HomeNewProductDelete",
			Handler:    _Sms_HomeNewProductDelete_Handler,
		},
		{
			MethodName: "HomeRecommendProductAdd",
			Handler:    _Sms_HomeRecommendProductAdd_Handler,
		},
		{
			MethodName: "HomeRecommendProductList",
			Handler:    _Sms_HomeRecommendProductList_Handler,
		},
		{
			MethodName: "HomeRecommendProductUpdate",
			Handler:    _Sms_HomeRecommendProductUpdate_Handler,
		},
		{
			MethodName: "HomeRecommendProductDelete",
			Handler:    _Sms_HomeRecommendProductDelete_Handler,
		},
		{
			MethodName: "HomeRecommendSubjectAdd",
			Handler:    _Sms_HomeRecommendSubjectAdd_Handler,
		},
		{
			MethodName: "HomeRecommendSubjectList",
			Handler:    _Sms_HomeRecommendSubjectList_Handler,
		},
		{
			MethodName: "HomeRecommendSubjectUpdate",
			Handler:    _Sms_HomeRecommendSubjectUpdate_Handler,
		},
		{
			MethodName: "HomeRecommendSubjectDelete",
			Handler:    _Sms_HomeRecommendSubjectDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/front/admin/v1/sms.proto",
}
