// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// 机构管理
type SysDept struct {
	Id             int64     `gorm:"column:id;AUTO_INCREMENT;primary_key"`                  // 编号
	Name           string    `gorm:"column:name"`                                           // 机构名称
	ParentId       int64     `gorm:"column:parent_id"`                                      // 上级机构ID，一级机构为0
	OrderNum       int       `gorm:"column:order_num"`                                      // 排序
	CreateBy       string    `gorm:"column:create_by"`                                      // 创建人
	CreateTime     time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 创建时间
	LastUpdateBy   string    `gorm:"column:last_update_by"`                                 // 更新人
	LastUpdateTime time.Time `gorm:"column:last_update_time"`                               // 更新时间
	DelFlag        int       `gorm:"column:del_flag;default:0"`                             // 是否删除  -1：已删除  0：正常
}

func (m *SysDept) TableName() string {
	return "sys_dept"
}

// 字典表
type SysDict struct {
	Id             int64     `gorm:"column:id;AUTO_INCREMENT;primary_key"`                  // 编号
	Value          string    `gorm:"column:value;NOT NULL"`                                 // 数据值
	Label          string    `gorm:"column:label;NOT NULL"`                                 // 标签名
	Type           string    `gorm:"column:type;NOT NULL"`                                  // 类型
	Description    string    `gorm:"column:description;NOT NULL"`                           // 描述
	Sort           string    `gorm:"column:sort;NOT NULL"`                                  // 排序（升序）
	CreateBy       string    `gorm:"column:create_by"`                                      // 创建人
	CreateTime     time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 创建时间
	LastUpdateBy   string    `gorm:"column:last_update_by"`                                 // 更新人
	LastUpdateTime time.Time `gorm:"column:last_update_time"`                               // 更新时间
	Remarks        string    `gorm:"column:remarks"`                                        // 备注信息
	DelFlag        int       `gorm:"column:del_flag;default:0"`                             // 是否删除  -1：已删除  0：正常
}

func (m *SysDict) TableName() string {
	return "sys_dict"
}

// 职位管理
type SysJob struct {
	Id             int64     `gorm:"column:id;AUTO_INCREMENT;primary_key"`                  // 编号
	JobName        string    `gorm:"column:job_name"`                                       // 职位名称
	OrderNum       int       `gorm:"column:order_num"`                                      // 排序
	CreateBy       string    `gorm:"column:create_by"`                                      // 创建人
	CreateTime     time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 创建时间
	LastUpdateBy   string    `gorm:"column:last_update_by"`                                 // 更新人
	LastUpdateTime time.Time `gorm:"column:last_update_time"`                               // 更新时间
	DelFlag        int       `gorm:"column:del_flag;default:0"`                             // 是否删除  -1：已删除  0：正常
	Remarks        string    `gorm:"column:remarks"`                                        // 备注
}

func (m *SysJob) TableName() string {
	return "sys_job"
}

// 系统登录日志
type SysLoginLog struct {
	Id             int64     `gorm:"column:id;AUTO_INCREMENT;primary_key"`                  // 编号
	UserName       string    `gorm:"column:user_name"`                                      // 用户名
	Status         string    `gorm:"column:status"`                                         // 登录状态（online:在线，登录初始状态，方便统计在线人数；login:退出登录后将online置为login；logout:退出登录）
	Ip             string    `gorm:"column:ip"`                                             // IP地址
	CreateBy       string    `gorm:"column:create_by"`                                      // 创建人
	CreateTime     time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 创建时间
	LastUpdateBy   string    `gorm:"column:last_update_by"`                                 // 更新人
	LastUpdateTime time.Time `gorm:"column:last_update_time"`                               // 更新时间
}

func (m *SysLoginLog) TableName() string {
	return "sys_login_log"
}

// 菜单管理
type SysMenu struct {
	Id             int64     `gorm:"column:id;AUTO_INCREMENT;primary_key"` // 编号
	Name           string    `gorm:"column:name"`                          // 菜单名称
	ParentId       int64     `gorm:"column:parent_id"`                     // 父菜单ID，一级菜单为0
	Url            string    `gorm:"column:url"`
	Perms          string    `gorm:"column:perms"`                                          // 授权(多个用逗号分隔，如：sys:user:add,sys:user:edit)
	Type           int       `gorm:"column:type"`                                           // 类型   0：目录   1：菜单   2：按钮
	Icon           string    `gorm:"column:icon"`                                           // 菜单图标
	OrderNum       int       `gorm:"column:order_num"`                                      // 排序
	CreateBy       string    `gorm:"column:create_by"`                                      // 创建人
	CreateTime     time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 创建时间
	LastUpdateBy   string    `gorm:"column:last_update_by"`                                 // 更新人
	LastUpdateTime time.Time `gorm:"column:last_update_time"`                               // 更新时间
	DelFlag        int       `gorm:"column:del_flag;default:0"`                             // 是否删除  -1：已删除  0：正常
}

func (m *SysMenu) TableName() string {
	return "sys_menu"
}

// 角色管理
type SysRole struct {
	Id             int64     `gorm:"column:id;AUTO_INCREMENT;primary_key"`                  // 编号
	Name           string    `gorm:"column:name"`                                           // 角色名称
	Remark         string    `gorm:"column:remark"`                                         // 备注
	CreateBy       string    `gorm:"column:create_by"`                                      // 创建人
	CreateTime     time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 创建时间
	LastUpdateBy   string    `gorm:"column:last_update_by"`                                 // 更新人
	LastUpdateTime time.Time `gorm:"column:last_update_time"`                               // 更新时间
	DelFlag        int       `gorm:"column:del_flag;default:0"`                             // 是否删除  -1：已删除  0：正常
	Status         int       `gorm:"column:status;default:1"`                               // 状态  1:启用,0:禁用
}

func (m *SysRole) TableName() string {
	return "sys_role"
}

// 角色机构
type SysRoleDept struct {
	Id             int64     `gorm:"column:id;AUTO_INCREMENT;primary_key"`                  // 编号
	RoleId         int64     `gorm:"column:role_id"`                                        // 角色ID
	DeptId         int64     `gorm:"column:dept_id"`                                        // 机构ID
	CreateBy       string    `gorm:"column:create_by"`                                      // 创建人
	CreateTime     time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 创建时间
	LastUpdateBy   string    `gorm:"column:last_update_by"`                                 // 更新人
	LastUpdateTime time.Time `gorm:"column:last_update_time"`                               // 更新时间
}

func (m *SysRoleDept) TableName() string {
	return "sys_role_dept"
}

// 角色菜单
type SysRoleMenu struct {
	Id             int64     `gorm:"column:id;AUTO_INCREMENT;primary_key"`                  // 编号
	RoleId         int64     `gorm:"column:role_id"`                                        // 角色ID
	MenuId         int64     `gorm:"column:menu_id"`                                        // 菜单ID
	CreateBy       string    `gorm:"column:create_by"`                                      // 创建人
	CreateTime     time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 创建时间
	LastUpdateBy   string    `gorm:"column:last_update_by"`                                 // 更新人
	LastUpdateTime time.Time `gorm:"column:last_update_time"`                               // 更新时间
}

func (m *SysRoleMenu) TableName() string {
	return "sys_role_menu"
}

// 用户管理
type SysUser struct {
	Id             int64     `gorm:"column:id;AUTO_INCREMENT;primary_key"`                  // 编号
	Name           string    `gorm:"column:name;NOT NULL"`                                  // 用户名
	NickName       string    `gorm:"column:nick_name"`                                      // 昵称
	Avatar         string    `gorm:"column:avatar"`                                         // 头像
	Password       string    `gorm:"column:password"`                                       // 密码
	Salt           string    `gorm:"column:salt"`                                           // 加密盐
	Email          string    `gorm:"column:email"`                                          // 邮箱
	Mobile         string    `gorm:"column:mobile"`                                         // 手机号
	Status         int       `gorm:"column:status"`                                         // 状态  0：禁用   1：正常
	DeptId         int64     `gorm:"column:dept_id"`                                        // 机构ID
	CreateBy       string    `gorm:"column:create_by"`                                      // 创建人
	CreateTime     time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;NOT NULL"` // 创建时间
	LastUpdateBy   string    `gorm:"column:last_update_by"`                                 // 更新人
	LastUpdateTime time.Time `gorm:"column:last_update_time"`                               // 更新时间
	DelFlag        int       `gorm:"column:del_flag;default:0"`                             // 是否删除  -1：已删除  0：正常
	JobId          int       `gorm:"column:job_id"`                                         // 岗位Id
}

func (m *SysUser) TableName() string {
	return "sys_user"
}

// 用户角色
type SysUserRole struct {
	Id             int64     `gorm:"column:id;AUTO_INCREMENT;primary_key"`         // 编号
	UserId         int64     `gorm:"column:user_id"`                               // 用户ID
	RoleId         int64     `gorm:"column:role_id"`                               // 角色ID
	CreateBy       string    `gorm:"column:create_by"`                             // 创建人
	CreateTime     time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP"` // 创建时间
	LastUpdateBy   string    `gorm:"column:last_update_by"`                        // 更新人
	LastUpdateTime time.Time `gorm:"column:last_update_time"`                      // 更新时间
}

func (m *SysUserRole) TableName() string {
	return "sys_user_role"
}
